apiVersion: batch/v1
kind: CronJob
metadata:
  name: run-full-export
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: run-full-export
            image: gcr.io/hikma-nica-clinic/hikma-health-backend:5f2761a6844bc457e3c775ff1b2aede86a9197da
            command:
            - /bin/bash
            - run-export.sh
          restartPolicy: OnFailure
